name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install the jvm
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - name: check out code
      uses: actions/checkout@v3
    - name: test code
      run: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test
    - name: remove cache locks
      run: find $HOME/.sbt -name "*.lock" | xargs rm